### ISSUE TITLE
change font maybe?

### ISSUE THREAD

**Issue by BraydenTW** [joshternyak/joshcodes#2]
Hey Josh.

I really like your website and it's design. If there was one thing to point out it would be to change the main font. Source Code Pro is bad, but I would suggest something like Poppins or Roboto to make your site look more modern.

Just my advice.

Have a good day.

**Comment by joshternyak** [comment]
Hey Brayden, I will change the font to Roboto right now, thanks for the advice. Also, you and I could possible do some projects together in the near future, just a thought.

**Comment by BraydenTW** [comment]
Thanks! That would be nice. Have a good day.
